-- MySQL Script generated by MySQL Workbench
-- Thu Oct 13 21:29:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema molla_store_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `molla_store_db` ;

-- -----------------------------------------------------
-- Schema molla_store_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `molla_store_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `molla_store_db` ;

-- -----------------------------------------------------
-- Table `molla_store_db`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`brand` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`brand` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_g7ft8mes72rnsk746b7ibyln2` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`users` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `auth_provider` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `enabled` BIT(1) NOT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_login` DATE NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `registered_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UK_6dotkott2kjsp8vw4d0m25fb7` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK_du5v5sr43g5bfnji4vb8hg5s3` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`cart` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`cart` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `create_at` DATETIME(6) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `line1` VARCHAR(50) NULL DEFAULT NULL,
  `line2` VARCHAR(50) NULL DEFAULT NULL,
  `mobile` VARCHAR(15) NULL DEFAULT NULL,
  `province` VARCHAR(50) NULL DEFAULT NULL,
  `published_at` DATE NULL DEFAULT NULL,
  `session_id` VARCHAR(100) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `update_at` DATE NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKg5uhi8vpsuy0lgloxk2h4w5o6` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKg5uhi8vpsuy0lgloxk2h4w5o6`
    FOREIGN KEY (`user_id`)
    REFERENCES `molla_store_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`product` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `create_at` DATETIME(6) NOT NULL,
  `discount` DOUBLE NOT NULL,
  `ends_at` DATETIME(6) NULL DEFAULT NULL,
  `price` DOUBLE NOT NULL,
  `published_at` DATETIME(6) NULL DEFAULT NULL,
  `quantity` INT NOT NULL,
  `rating` DOUBLE NULL DEFAULT NULL,
  `sku` VARCHAR(100) NOT NULL,
  `start_at` DATETIME(6) NULL DEFAULT NULL,
  `title` VARCHAR(75) NOT NULL,
  `update_at` DATETIME(6) NULL DEFAULT NULL,
  `brand_id` BIGINT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKs6cydsualtsrprvlf2bb3lcam` (`brand_id` ASC) VISIBLE,
  INDEX `FK47nyv78b35eaufr6aa96vep6n` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK47nyv78b35eaufr6aa96vep6n`
    FOREIGN KEY (`user_id`)
    REFERENCES `molla_store_db`.`users` (`user_id`),
  CONSTRAINT `FKs6cydsualtsrprvlf2bb3lcam`
    FOREIGN KEY (`brand_id`)
    REFERENCES `molla_store_db`.`brand` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`cart_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`cart_item` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`cart_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `active` BIT(1) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `create_at` DATETIME(6) NOT NULL,
  `discount` DOUBLE NOT NULL,
  `price` DOUBLE NOT NULL,
  `published_at` DATETIME(6) NULL DEFAULT NULL,
  `quantity` INT NOT NULL,
  `sku` VARCHAR(100) NOT NULL,
  `update_at` DATETIME(6) NULL DEFAULT NULL,
  `cart_id` BIGINT NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1uobyhgl1wvgt1jpccia8xxs3` (`cart_id` ASC) VISIBLE,
  INDEX `FKjcyd5wv4igqnw413rgxbfu4nv` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK1uobyhgl1wvgt1jpccia8xxs3`
    FOREIGN KEY (`cart_id`)
    REFERENCES `molla_store_db`.`cart` (`id`),
  CONSTRAINT `FKjcyd5wv4igqnw413rgxbfu4nv`
    FOREIGN KEY (`product_id`)
    REFERENCES `molla_store_db`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`category` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_acatplu22q5d1andql2jbvjy7` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`orders` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `create_at` DATETIME(6) NOT NULL,
  `discount` DOUBLE NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `grand_total` DOUBLE NOT NULL,
  `item_discount` DOUBLE NOT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `line1` VARCHAR(50) NULL DEFAULT NULL,
  `line2` VARCHAR(50) NULL DEFAULT NULL,
  `mobile` VARCHAR(15) NULL DEFAULT NULL,
  `promo` VARCHAR(50) NULL DEFAULT NULL,
  `province` VARCHAR(50) NULL DEFAULT NULL,
  `published_at` DATE NULL DEFAULT NULL,
  `session_id` VARCHAR(100) NOT NULL,
  `shipping` DOUBLE NOT NULL,
  `status` INT NOT NULL,
  `subtotal` DOUBLE NOT NULL,
  `tax` DOUBLE NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `total` DOUBLE NOT NULL,
  `update_at` DATE NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK32ql8ubntj5uh44ph9659tiih` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK32ql8ubntj5uh44ph9659tiih`
    FOREIGN KEY (`user_id`)
    REFERENCES `molla_store_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`order_item` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `create_at` DATETIME(6) NOT NULL,
  `discount` DOUBLE NOT NULL,
  `price` DOUBLE NOT NULL,
  `published_at` DATE NULL DEFAULT NULL,
  `quantity` INT NOT NULL,
  `sku` VARCHAR(100) NOT NULL,
  `update_at` DATE NULL DEFAULT NULL,
  `order_id` BIGINT NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKt4dc2r9nbvbujrljv3e23iibt` (`order_id` ASC) VISIBLE,
  INDEX `FK551losx9j75ss5d6bfsqvijna` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK551losx9j75ss5d6bfsqvijna`
    FOREIGN KEY (`product_id`)
    REFERENCES `molla_store_db`.`product` (`id`),
  CONSTRAINT `FKt4dc2r9nbvbujrljv3e23iibt`
    FOREIGN KEY (`order_id`)
    REFERENCES `molla_store_db`.`orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`p_color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`p_color` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`p_color` (
  `p_color_id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`p_color_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`p_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`p_image` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`p_image` (
  `p_image_id` BIGINT NOT NULL AUTO_INCREMENT,
  `p_image_large` VARCHAR(255) NULL DEFAULT NULL,
  `p_image_medium` VARCHAR(255) NULL DEFAULT NULL,
  `p_image_small` VARCHAR(255) NULL DEFAULT NULL,
  `p_color_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`p_image_id`),
  INDEX `FK9kswywtfuomrkdjqbaj0dub28` (`p_color_id` ASC) VISIBLE,
  CONSTRAINT `FK9kswywtfuomrkdjqbaj0dub28`
    FOREIGN KEY (`p_color_id`)
    REFERENCES `molla_store_db`.`p_color` (`p_color_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`product_category` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`product_category` (
  `product_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  INDEX `FKkud35ls1d40wpjb5htpp14q4e` (`category_id` ASC) VISIBLE,
  INDEX `FK2k3smhbruedlcrvu6clued06x` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK2k3smhbruedlcrvu6clued06x`
    FOREIGN KEY (`product_id`)
    REFERENCES `molla_store_db`.`product` (`id`),
  CONSTRAINT `FKkud35ls1d40wpjb5htpp14q4e`
    FOREIGN KEY (`category_id`)
    REFERENCES `molla_store_db`.`category` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`product_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`product_image` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`product_image` (
  `product_id` BIGINT NOT NULL,
  `p_image_id` BIGINT NOT NULL,
  INDEX `FK49pmynpild3ribjccjy04vfch` (`p_image_id` ASC) VISIBLE,
  INDEX `FK6oo0cvcdtb6qmwsga468uuukk` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK49pmynpild3ribjccjy04vfch`
    FOREIGN KEY (`p_image_id`)
    REFERENCES `molla_store_db`.`p_image` (`p_image_id`),
  CONSTRAINT `FK6oo0cvcdtb6qmwsga468uuukk`
    FOREIGN KEY (`product_id`)
    REFERENCES `molla_store_db`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`product_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`product_review` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`product_review` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `published` BIT(1) NOT NULL,
  `published_at` DATETIME(6) NULL DEFAULT NULL,
  `rating` INT NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  `parent_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKkaqmhakwt05p3n0px81b9pdya` (`product_id` ASC) VISIBLE,
  INDEX `FKmw8bh2e19mh773k1wcu20xtc1` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `FKkaqmhakwt05p3n0px81b9pdya`
    FOREIGN KEY (`product_id`)
    REFERENCES `molla_store_db`.`product` (`id`),
  CONSTRAINT `FKmw8bh2e19mh773k1wcu20xtc1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `molla_store_db`.`product_review` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`roles` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`roles` (
  `role_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `UK_ofx66keruapi6vyqpv6f2or37` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`transaction` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`transaction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(100) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `create_at` DATETIME(6) NOT NULL,
  `mode` INT NULL DEFAULT NULL,
  `published_at` DATE NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `type` INT NULL DEFAULT NULL,
  `update_at` DATE NULL DEFAULT NULL,
  `order_id` BIGINT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKa8ufxrrpq6xmniblly0v1rhu8` (`order_id` ASC) VISIBLE,
  INDEX `FKanjpo5tiapru7an6cw4cu37y4` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKa8ufxrrpq6xmniblly0v1rhu8`
    FOREIGN KEY (`order_id`)
    REFERENCES `molla_store_db`.`orders` (`id`),
  CONSTRAINT `FKanjpo5tiapru7an6cw4cu37y4`
    FOREIGN KEY (`user_id`)
    REFERENCES `molla_store_db`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `molla_store_db`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `molla_store_db`.`user_role` ;

CREATE TABLE IF NOT EXISTS `molla_store_db`.`user_role` (
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  INDEX `FKt7e7djp752sqn6w22i6ocqy6q` (`role_id` ASC) VISIBLE,
  INDEX `FKj345gk1bovqvfame88rcx7yyx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKj345gk1bovqvfame88rcx7yyx`
    FOREIGN KEY (`user_id`)
    REFERENCES `molla_store_db`.`users` (`user_id`),
  CONSTRAINT `FKt7e7djp752sqn6w22i6ocqy6q`
    FOREIGN KEY (`role_id`)
    REFERENCES `molla_store_db`.`roles` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
